{
    "settings": {
        "style": {
            "background_class": "",
            "background-color": "rgb(47, 48, 60)"
        },
        "theme": "redmond",
        "sizex": "1275",
        "sizey": "1500",
        "gridSize": "",
        "snapType": null,
        "useBackground": false,
        "alwaysRender": false,
        "useAsDefault": false
    },
    "widgets": {
        "e00001": {
            "tpl": "tplHtml",
            "data": {
                "g_fixed": false,
                "g_visibility": false,
                "g_css_font_text": true,
                "g_css_background": true,
                "g_css_shadow_padding": false,
                "g_css_border": false,
                "g_gestures": false,
                "g_signals": false,
                "g_last_change": false,
                "visibility-cond": "==",
                "visibility-val": 1,
                "visibility-groups-action": "hide",
                "refreshInterval": "0",
                "signals-cond-0": "==",
                "signals-val-0": true,
                "signals-icon-0": "/vis/signals/lowbattery.png",
                "signals-icon-size-0": 0,
                "signals-blink-0": false,
                "signals-horz-0": 0,
                "signals-vert-0": 0,
                "signals-hide-edit-0": false,
                "signals-cond-1": "==",
                "signals-val-1": true,
                "signals-icon-1": "/vis/signals/lowbattery.png",
                "signals-icon-size-1": 0,
                "signals-blink-1": false,
                "signals-horz-1": 0,
                "signals-vert-1": 0,
                "signals-hide-edit-1": false,
                "signals-cond-2": "==",
                "signals-val-2": true,
                "signals-icon-2": "/vis/signals/lowbattery.png",
                "signals-icon-size-2": 0,
                "signals-blink-2": false,
                "signals-horz-2": 0,
                "signals-vert-2": 0,
                "signals-hide-edit-2": false,
                "lc-type": "last-change",
                "lc-is-interval": true,
                "lc-is-moment": false,
                "lc-format": "",
                "lc-position-vert": "top",
                "lc-position-horz": "right",
                "lc-offset-vert": 0,
                "lc-offset-horz": 0,
                "lc-font-size": "12px",
                "lc-font-family": "",
                "lc-font-style": "",
                "lc-bkg-color": "",
                "lc-color": "",
                "lc-border-width": "0",
                "lc-border-style": "",
                "lc-border-color": "",
                "lc-border-radius": 10,
                "lc-zindex": 0,
                "html": "<br><br><b><font color='#52fffb'>\nLadeschwelle =</font></b>&nbsp; Bis zu diesem SoC Wert wird sofort mit der gesamten überschüssigen PV-Leistung geladen. Erst wenn die Ladeschwelle erreicht wird, wird mit dem geregelten Laden begonnen\n<br><br><b><font color='#52fffb'>\nLadeende =</font></b>&nbsp; SoC Wert Speicher, der zum Ende des Regelzeitraums erreicht werden soll.\n<br><br><b><font color='#52fffb'>\nLadeende2 =</font></b>&nbsp; Parameter Sommerladeende gibt die Zeit vor, bis zu der der SOC Ladeende2 erreicht werden sollten. \n<br><br><b><font color='#52fffb'>\nSommer Ladeende =</font></b>&nbsp; Zeit bis zu der der Batteriespeicher den SOC Wert im Parameter \"Ladeende2\" erreichen soll\n<br><br><b><font color='#52fffb'>\nWinter Minimum =</font></b>&nbsp; Beginn des Regelzeitraums am 21.12. GMT/UTC dezimal.\n<br><br><b><font color='#52fffb'>\nSommer Maximum =</font></b>&nbsp; Beginn des Regelzeitraums am 21.6. GMT/UTC dezimal.\n<br><br><b><font color='#52fffb'>\nUnload =</font></b>&nbsp; wenn der SoC Wert der Batterie > Wert „Unload“ ist, wird der Batteriespeicher mit Beginn Solarproduktion bis Beginn Regelzeitraum (Definition und Berechnung siehe unten), auf SOC Wert Parameter \"Unload\" entladen.\nErst wenn die Ladeschwelle erreicht wird, wird mit dem geregelten Laden begonnen. Danach wird bis SOC Wert „Ladeende“ gleichmäßig geladen, mit Ausnahme, wenn die PV-Leistung das Einspeiselimit oder die WR-Maxleistung übersteigt, wird die Ladeleistung um den Wert erhöht, um das Einspeiselimit oder WR-Limit einhalten zu können. Bei unterschreiten von dem Wert Einspeiselimit oder WR-Limit, wird wieder mit neu berechneter Ladeleistung, gleichmäßig bis „Ladeende\" geladen. Bei großem Überschuss kann die gleichmäßige Ladeleistung bis auf 0 abgesenkt werden.\nParameter \"Ladeschwelle\" hat Vorrang vor \"Unload\", d.h. \"Unload\" wird ignoriert, falls \"Ladeschwelle\" größer sein sollte als „Unload“.\n<br><br><b><font color='#52fffb'>\nUnterer Ladekorridor =</font></b>&nbsp; Der „Untere Ladekorridor“ definiert nur den min. Wert ab dem mit dem Laden der Batterie gestartet wird.\n<br><br><b><font color='#52fffb'>\nNotstrom min =</font></b>&nbsp; Speicherreserve in % bei Wintersonnenwende 21.12\n<br><br><b><font color='#52fffb'>\nNotstrom Sockel =</font></b>&nbsp; min. SOC Wert bei Tag-/Nachtgleiche 21.3./21.9.<br> Mit Notstrom min. und Notstrom Sockel kann man eine Dynamische Notstromreserve vorhalten, Vorteil ist das der Speicher nicht alle 3 Wochen entladen wird wie bei der Notstromreserve von E3DC.\n<br><br><b><font color='#52fffb'>\nEigenverbrauch =</font></b>&nbsp; Der geschätzte Eigenverbrauch pro Tag in kWh. Wird für die Überschussberechnung der Prognose verwendet.\n"
            },
            "style": {
                "left": "8px",
                "top": "-1px",
                "width": "1260px",
                "height": "985px",
                "color": "#ffffff",
                "background-color": "rgb(47, 48, 60)"
            },
            "widgetSet": "basic"
        }
    },
    "name": "Info_1",
    "filterList": []
}